### PR TITLE
New screencast documentation

### PR DESCRIPTION
**Pull request by codepo8**
Preview What's New: [https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/11/devtools?branch=pr-en-us-1922](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/11/devtools?branch=pr-en-us-1922)

Preview Extension: [https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension?branch=pr-en-us-1922](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension?branch=pr-en-us-1922)

### CODE REVIEW

**Comment by codepo8** [comment]
Any news on that? Release is on 5/4

**Review by vchapel — APPROVED** [review]
LGTM

**Comment by codepo8** [comment]
@vchapel @mikehoffms @Reezaali This went live today, can we release?

**Comment by captainbrosset** [comment]
Since this is now approved, I will merge to main and push live.

**Pull request merged**
