### PR TITLE
chore: Add Markdownlint CI

### PR DESCRIPTION
**Pull request by nschonni**
Runs Markdownlint if a push or PR contains MD files.

### CODE REVIEW

**Comment by nschonni** [comment]
@jm-trd-ms you can see it running over on the Dotnet docs here https://github.com/dotnet/docs/actions?query=workflow%3AMarkdownlint

**Comment by nschonni** [comment]
@jm-trd-ms did you have any questions about this?

**Comment by jm-trd-ms** [comment]
@nschonni,  
We appreciate your suggestion to add markdowlint functionality to our repo.  
At this time, we have decide to not move forward with the implementation.  
We may revisit implementing it in the future.  

We look forward to your continued suggestions.  

Thank you

**Comment by nschonni** [comment]
@jm-trd-ms here's the steps you can use if you decide you want to do some of the automated fixes in the future:
1. `npm i -g markdownlint-cli` to get the commandline tool
1. Disable the individual rule that can auto-fix like this one by removing the line in the config
1. Run `markdownlint --fix "**/*.md"` to auto-fix

I'd recommend enabling some sort of CI eventually, but i'll stop sending PRs

**Pull request closed without merging**
