### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
The original link is not available, removed link and left just as a text.

### CODE REVIEW

**Comment by DhurataJ** [comment]
@tfosmark - Please can you verify and merge this PR. Thanks!

**Comment by DhurataJ** [comment]
@tfosmark - Please can you verify and merge this PR. Thanks!

Note: It's the case where the link was inside the content from some original page where no longer couldn't found. In edit file the link was removed, for some reasons it was still active in source article.

**Comment by tfosmark** [comment]
@DhurataJ On line 281, you want to make this change:
> The original page was found at `https://developers.google.com/web/tools/chrome-devtools/beginners/html`  and was authored by [Katherine Jackson](https://developers.google.com/web/resources/contributors#katherine-jackson) (Technical Writer Intern, Chrome DevTools).

The backticks cause the string to be treated as formatted text rather than a URL string.

**Comment by DhurataJ** [comment]
> s found at `h`

@tfosmark - Yes, Tami in that particular case. I tried to put this brackets [ ] to hide it but it doesn't seem good to someone who is reading article. Is there any way on treating that as a text?

**Comment by tfosmark** [comment]
**Global effort to fix broken links**

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Comment by tfosmark** [comment]
@mikehoffms Can you please merge this fix? Thank you!

**Review by vchapel — APPROVED** [review]
LGTM

**Pull request merged**
