### PR TITLE
edit pass: extensions.md (work item 1574243)

### PR DESCRIPTION
**Pull request by ktoliver**
@boyofgreen @mccoykillian @balajek - These are the proposed edits for the **extensions.md** article in Azure DevOps work item [1574243](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1574243). Please review the copy edits within five business days and let me know if I changed the technical meaning anywhere. 

Thank you.

### CODE REVIEW

**Comment by ktoliver** [comment]
@boyofgreen @mccoykillian @balajek - Have you had a chance to review the edits? I don't have merge permissions for the repo. Could one of you merge the PR or give feedback on items in the edit pass that you might want to see changed? Thanks very much.

@ShawnJackson @tfosmark

**Comment by ktoliver** [comment]
@zoherghadyali Would you be able to merge this PR? Thanks!

**Comment by tfosmark** [comment]
This PR has been open too long & the file has changed. 

#please-close

**Comment by jm-trd-ms** [comment]
#close per @tfosmark

**Pull request closed without merging**
