### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by Shahina-Jindal**

### CODE REVIEW

**Comment by jm-trd-ms** [comment]
I added the index.html file and updated the markdown content for hosting-and-updating and match-patterns. 
@Shahina-Jindal  Please confirm the changes ands I will sign off and merge.

**Comment by Shahina-Jindal** [comment]
Hello Joe,

Please go ahead and merge changes.

Thanks,
Shahina

**Comment by jm-trd-ms** [comment]
Merging per @Shahina-Jindal

**Comment by jm-trd-ms** [comment]
Deleting Branch: `extensions`

**Pull request merged**
