### PR TITLE
Windows Store app to UWP app, Windows Store to Microsoft Store

### PR DESCRIPTION
**Pull request by mijacobs**
On 10/26, the Windows Store is changing its name to the Microsoft Store.  To prepare for the name change, I’ve made these changes :

•	Windows Store -> Microsoft Store
•	Windows Store app -> UWP app
•	Xbox Store -> Microsoft Store

### CODE REVIEW

**Comment by abbycar** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions/getting-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/getting-started.md) | :warning:Warning | | [Details](#user-content-microsoft-edge%2Fextensions%2Fgetting-started.md)
[microsoft-edge/extensions/guides/packaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging.md) | :warning:Warning | | [Details](#user-content-microsoft-edge%2Fextensions%2Fguides%2Fpackaging.md)
[microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md) | :warning:Warning | | [Details](#user-content-microsoft-edge%2Fextensions%2Fguides%2Fpackaging%2Fusing-manifoldjs-to-package-extensions.md)
[microsoft-edge/extensions/extensions-for-enterprise.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/extensions-for-enterprise.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/design.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/design.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/native-messaging.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/extensions-in-the-windows-dev-center.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/extensions-in-the-windows-dev-center.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/running-the-windows-app-certification-kit.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/running-the-windows-app-certification-kit.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/microsoft-browser-extension-policy.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/microsoft-browser-extension-policy.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/tips-and-tricks.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/tips-and-tricks.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/troubleshooting.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/troubleshooting.md) | :white_check_mark:Succeeded | |

<a name="microsoft-edge%2Fextensions%2Fgetting-started.md"></a>
### [microsoft-edge/extensions/getting-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/getting-started.md)
 - **Line 71**: **[Warning]** Illegal link: `[does not have a transparent background](./guides/design.md#windows-store-icon)` -- missing bookmark. The file extensions/guides/design.md doesn&#39;t contain a bookmark named windows-store-icon.
 - **Line 73**: **[Warning]** Illegal link: `[deep-link to your extension in the Microsoft Store](./tips-and-tricks.md#get-a-direct-link-to-your-extension-in-the-windows-store)` -- missing bookmark. The file extensions/tips-and-tricks.md doesn&#39;t contain a bookmark named get-a-direct-link-to-your-extension-in-the-windows-store.

<a name="microsoft-edge%2Fextensions%2Fguides%2Fpackaging.md"></a>
### [microsoft-edge/extensions/guides/packaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging.md)
 - **Line 46**: **[Warning]** Illegal link: `[Localizing name and description for the Microsoft Store](./packaging/localizing-extension-packages.md#localizing-name-and-description-in-the-windows-store)` -- missing bookmark. The file extensions/guides/packaging/localizing-extension-packages.md doesn&#39;t contain a bookmark named localizing-name-and-description-in-the-windows-store.

<a name="microsoft-edge%2Fextensions%2Fguides%2Fpackaging%2Fusing-manifoldjs-to-package-extensions.md"></a>
### [microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md)
 - **Line 93**: **[Warning]** Illegal link: `[Localizing name and description in the Microsoft Store](./localizing-extension-packages.md#localizing-name-and-description-in-the-windows-store)` -- missing bookmark. The file extensions/guides/packaging/localizing-extension-packages.md doesn&#39;t contain a bookmark named localizing-name-and-description-in-the-windows-store.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C19%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C201710191543080072-44%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5P5n3HHMMv1VK2eae5G%2F8sDnX99BMBdE2S70w%2FcoKpw%3D&st=2017-10-19T15%3A39%3A14Z&se=2017-11-19T15%3A44%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by abbycar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions/extensions-for-enterprise.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/extensions-for-enterprise.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/getting-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/getting-started.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/design.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/design.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/native-messaging.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/extensions-in-the-windows-dev-center.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/extensions-in-the-windows-dev-center.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/running-the-windows-app-certification-kit.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/running-the-windows-app-certification-kit.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/microsoft-browser-extension-policy.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/microsoft-browser-extension-policy.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/tips-and-tricks.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/tips-and-tricks.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/troubleshooting.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/troubleshooting.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C19%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C201710191552096830-44%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZBmHjGwwhNTMITmJ2WOWwqrNQV0RI1W8VmsknJKU1AM%3D&st=2017-10-19T15%3A47%3A54Z&se=2017-11-19T15%3A52%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by abbycar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions/extensions-for-enterprise.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/extensions-for-enterprise.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/getting-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/getting-started.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/design.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/design.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/native-messaging.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/extensions-in-the-windows-dev-center.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/extensions-in-the-windows-dev-center.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/running-the-windows-app-certification-kit.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/running-the-windows-app-certification-kit.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/microsoft-browser-extension-policy.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/microsoft-browser-extension-policy.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/tips-and-tricks.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/tips-and-tricks.md) | :white_check_mark:Succeeded | |
[microsoft-edge/extensions/troubleshooting.md](https://github.com/MicrosoftDocs/edge-developer/blob/store-terminology-updates/microsoft-edge/extensions/troubleshooting.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C20%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C201710201725405289-44%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Lh3LrF676aFd57qugZoNvBdx5F5YBFONpRA3IKiBSPU%3D&st=2017-10-20T17%3A21%3A21Z&se=2017-11-20T17%3A26%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by erikadoyle** [comment]
LGTM. Vielen Dank, @mijacobs !

**Pull request merged**
