### PR TITLE
v-jandrew/Commenting out Link for Windows-user-Folder.md

### PR DESCRIPTION
**Pull request by JasonAndrewWriter**
Until this link is fixed, I am commenting it out.

### CODE REVIEW

**Comment by JasonAndrewWriter** [comment]
This is for this workitem.  https://microsoft.visualstudio.com/Edge/_workitems/edit/41198877

**Comment by JasonAndrewWriter** [comment]
I forgot to do the requesting naming schema.  I dont think you can change it mid pr

**Comment by captainbrosset** [comment]
@JasonAndrewWriter this PR is marked as a draft, let me know when it's ready for review.

**Comment by JasonAndrewWriter** [comment]
> @JasonAndrewWriter this PR is marked as a draft, let me know when it's ready for review.

@captainbrosset Apoligies.  Forgot to click the button.  I edited out the link until the other work item is fixed.

**Review by captainbrosset — APPROVED** [review]

**Pull request merged**
