### PR TITLE
edit pass: error-and-status-codes

### PR DESCRIPTION
**Pull request by v-rihow**
Edit pass complete; ready for author review per https://github.com/MicrosoftDocs/edge-developer/pull/297#issuecomment-520102753.

### CODE REVIEW

**Comment by v-rihow** [comment]
The copy-edit to this article is tentatively complete, Please note the following comments, and let me know if I’ve changed the technical meaning anywhere. This is for Azure DevOps work request [1574241](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1574241/?triage=true).

Comments:

- In the "CSP codes" section, the CSP14305 row now has the following (right-most column): "The source site's address may include an optional leading wildcard (the asterisk character). For example, mail.foo.com:*." This has been changed from what was there initially, as the asterisk formatting wasn't resolving correctly. In any case, I need a transcription of exactly what this should say and how it should appear, and then I'll try to format it accordingly in Markdown.
- In the "SVG codes" section: it started with "tools don't currently support extensive Scalable Vector Graphics (SVG) debugging ...". I tentatively revised to "DevTools doesn't currently ...". Please verify that this is what was intended here.

**Comment by v-rihow** [comment]
#sign-off since review period has long since expired

**Comment by v-rihow** [comment]
#sign-off

**Comment by jm-trd-ms** [comment]
#sign-off and merge.

**Pull request merged**
