### PR TITLE
Migrate Selenium tools for MS Edge documentation the MicrosoftDocs and include Python samples

### PR DESCRIPTION
**Pull request by bwalderman**
This change updates the WebDriver (Chromium) page in the Edge Developer docs to be the single destination for info on WebDriver integration for both Selenium 3 and 4. This includes info on the Selenium Tools for Microsoft Edge. A separate change will remove the duplicate content from https://github.com/microsoft/edge-selenium-tools and update the project to link here instead.

Now that the python package is close to being published, I've added Python samples. Comments have been added to emphasize that the samples are usable in bot Selenium 3 and 4.

### CODE REVIEW

**Comment by zoherghadyali** [comment]
Overall looks good but I have some more changes I'd like to make. For the Python and C# samples, I think we should actually use tabs like in this doc: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator. The way to create tabs is shown here: https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/tabbed-conceptual?branch=master. 

I also think we should separate out the Selenium Tools for Microsoft Edge section into its own doc underneath WebDriver (Chromium). Then, from our Selenium 3 section, we can just point to it instead of embedding all of that content for Selenium Tools there.

I will try to get these changes in by EOD today but if you have the bandwidth, feel free to make them yourself and I'm happy to just review.

**Comment by bwalderman** [comment]
@zoherghadyali thanks, I wanted to do tabs as well but wasn't aware how to actually create those. I'll take a look.

 > I also think we should separate out the Selenium Tools for Microsoft Edge section into its own doc underneath WebDriver (Chromium). Then, from our Selenium 3 section, we can just point to it instead of embedding all of that content for Selenium Tools there.

We're essentially doing this already. The Selenium 3 contains a couple of short paragraphs explaining why the Tools are needed, and the "Install Selenium Tools for Microsoft Edge" link points to the github repo where detailed install instructions can be found.

**Comment by jm-trd-ms** [comment]
Based upon my reading about Tabs, it has been deprecated.
I will investigate further and respond here.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bwalderman** [comment]
@jm-trd-ms, using Chocolatey or Docker to install WebDriver is independent of what language you choose to write your tests in so I think these should be left out of the tab group.

I was also imagining a separate tab group for each individual code sample. The current approach requires us to maintain two copies of the same content (one for each tab).

@jm-trd-ms, @zoherghadyali what are your thoughts?

**Comment by jm-trd-ms** [comment]
#sign-off and merged.

**Pull request merged**
