### PR TITLE
Fixed keyboard shortcut to open settings

### PR DESCRIPTION
**Pull request by pankajparashar**
Pretty sure on MacOS, the keyboard shortcut to open Settings is `Shift+?`. Didn't check windows, but most likely it should be the same.

### CODE REVIEW

**Comment by captainbrosset** [comment]
@pankajparashar good point. On my keyboard, the `?` sign can only be accessed by pressing `Shift` first. So, the shortcut is indeed `Shift`+`?`. I wonder if there are other keyboard layouts where `?` can be accessed directly with no modifier.

@mikehoffms what do you think?

**Comment by pankajparashar** [comment]
This is what the tooltip on the Settings icon in Edge shows the keyboard shortcut,

image

**Review by captainbrosset — APPROVED** [review]

**Comment by captainbrosset** [comment]
Confirmed with Michael offline that we indeed need to add the Shift modifier in the doc. The ? key can only be accessed with Shift, on every keyboard.

**Comment by captainbrosset** [comment]
This change has been merged to the live branch and should be available any minute now.

**Pull request merged**
