### PR TITLE
Focus Mode screenshots for Memory-Problem-Images

### PR DESCRIPTION
**Pull request by JasonAndrewWriter**
date

### CODE REVIEW

**Review by captainbrosset — DISMISSED** [review]
Thanks Jason.

A few comments about this before we can merge:

1. `microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-dev-tools-performance.msft.png` and `microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-settings-more-tools-browser-task-manager.msft.png.png` are new images that you created. Since you didn't change any of the markdown content, there shouldn't need to be new images in this PR. This PR should only contain changes to existing images.
1. `microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-manager-javascript-memory.msft.png` does not need to be re-created in this PR. It doesn't show the UI of DevTools, so is not impacted by Focus Mode.
1. The other images in this PR show your taskbar. When taking a screenshot, please do the following first:
   * Set your desktop background to white.
   * Hide all other windows.
   * Un-maximize the window you want to capture so it sits nicely on the white background.
   * Use Snipping Tool's "Window mode" to capture the full window with its window borders.

This ensures that the screenshots we create are easy to embed in the docs, and don't show any personal information.

**Comment by JasonAndrewWriter** [comment]
I did #1 and #2.  Working on the rest.

**Comment by JasonAndrewWriter** [comment]
> Thanks Jason.
> 
> A few comments about this before we can merge:
> 
> 1. `microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-dev-tools-performance.msft.png` and `microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-settings-more-tools-browser-task-manager.msft.png.png` are new images that you created. Since you didn't change any of the markdown content, there shouldn't need to be new images in this PR. This PR should only contain changes to existing images.
> 2. `microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-manager-javascript-memory.msft.png` does not need to be re-created in this PR. It doesn't show the UI of DevTools, so is not impacted by Focus Mode.
> 3. The other images in this PR show your taskbar. When taking a screenshot, please do the following first:
>    
>    * Set your desktop background to white.
>    * Hide all other windows.
>    * Un-maximize the window you want to capture so it sits nicely on the white background.
>    * Use Snipping Tool's "Window mode" to capture the full window with its window borders.
> 
> This ensures that the screenshots we create are easy to embed in the docs, and don't show any personal information.

I think I fixed it

**Comment by JasonAndrewWriter** [comment]
I think the Dev-Tools (https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/landing/) is a little confusing.  I am going to try to clean it up a bit it word to hit the feedback given today and meeting with patrick tomorrow super early to get this streamlined.  And then redo.

**Comment by captainbrosset** [comment]
I merged main in this branch, to make sure it was up to date, removed 2 images that were changed in the PR but didn't really need to. And I updated a few screenshots to remove the QuickView at the bottom, to avoid confusing users.

**Review by captainbrosset — APPROVED** [review]

**Pull request merged**
