### PR TITLE
Update Site Impacting changes

### PR DESCRIPTION
**Pull request by ericlaw1979**
Note 3-digit UA string.
Postpone cross-origin dialog change

### CODE REVIEW

**Comment by ericlaw1979** [comment]
+ @mikehoffms

**Review by mikehoffms — APPROVED** [review]
@ericlaw1979 - Please techreview my commit; my rewording of the three-digit entry.  
What if the version # is 99, will `Edg/099` be returned instead of '`Edg/99`?  That might be an interesting example to provide.  
Will `Edg/099` ever be returned?  
Will `--enable-features=ForceMajorVersion100InUserAgent` always return `Edg/100`, or could it return `Edg/099`?

**Review by ericlaw1979 — COMMENTED** [review]
Your edit looks fine.

**Comment by ericlaw1979** [comment]
Edit looks fine. No, there's no case of a "Edg/099" version number.

The change here is that the version number is going from 99 to 100. The reason this is deemed a potentially-breaking change is only because of the fact that 100 has three digits while 99 has two. 

The command line flag does exactly what it says, it changes the major version to "100" even if it is really, say, 98.

**Pull request merged**
