### PR TITLE
Fix ms.service: issues found in content engagement report

### PR DESCRIPTION
**Pull request by msangapu-msft**
image

AB#49023826

### CODE REVIEW

**Review by Reezaali — APPROVED** [review]

**Comment by msangapu-msft** [comment]
#sign-off

**Comment by mikehoffms** [comment]
full-text search of repo on "ms.service:" reveals two instances to fix: landing page & hub page.  Then, all files will have same value.

**Comment by msangapu-msft** [comment]
> full-text search of repo on "ms.service:" reveals two instances to fix: landing page & hub page. Then, all files will have same value. Pushed commit to fix in hub page: \microsoft-edge\developer\index.yml

Thank you

**Review by mikehoffms — APPROVED** [review]
Checked valid values for ms.service: & ms.subservice:, for hub page (ok) & the two landing pages (fixed).

**Pull request merged**
