### PR TITLE
Aded IT pro link

### PR DESCRIPTION
**Pull request by MattLusherRO**

### CODE REVIEW

**Comment by abbycar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/index.md](https://github.com/MattLusherRO/edge-developer/blob/974366/microsoft-edge/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C19%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C201704192316113218-24%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by abbycar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/index.md](https://github.com/MattLusherRO/edge-developer/blob/974366/microsoft-edge/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C20%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C201704201713477004-24%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MattLusherRO** [comment]
@kimtapia

**Comment by mattwojo** [comment]
I've already got this change made and staged in the "landingpage" branch --- closing this out and not merging.

**Pull request closed without merging**
